// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricDatum.proto

package net.kylindb.analyser.mq;

public final class MetricDatum {
  private MetricDatum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetricDatumRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 pointId = 1;
    /**
     * <code>required int64 pointId = 1;</code>
     */
    boolean hasPointId();
    /**
     * <code>required int64 pointId = 1;</code>
     */
    long getPointId();

    // required int64 timestamp = 2;
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *数据采集时间戳，距离1970年1月1日原点的毫秒数。
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *数据采集时间戳，距离1970年1月1日原点的毫秒数。
     * </pre>
     */
    long getTimestamp();

    // required bytes value = 3;
    /**
     * <code>required bytes value = 3;</code>
     *
     * <pre>
     *测量点在该时间点上对应的值
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 3;</code>
     *
     * <pre>
     *测量点在该时间点上对应的值
     * </pre>
     */
    com.google.protobuf.ByteString getValue();

    // repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> 
        getNotesList();
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry getNotes(int index);
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    int getNotesCount();
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    java.util.List<? extends net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder> 
        getNotesOrBuilderList();
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder getNotesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.kylindb.analyser.mq.MetricDatumRequest}
   */
  public static final class MetricDatumRequest extends
      com.google.protobuf.GeneratedMessage
      implements MetricDatumRequestOrBuilder {
    // Use MetricDatumRequest.newBuilder() to construct.
    private MetricDatumRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MetricDatumRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MetricDatumRequest defaultInstance;
    public static MetricDatumRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MetricDatumRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MetricDatumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pointId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                notes_ = new java.util.ArrayList<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry>();
                mutable_bitField0_ |= 0x00000008;
              }
              notes_.add(input.readMessage(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          notes_ = java.util.Collections.unmodifiableList(notes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.class, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MetricDatumRequest> PARSER =
        new com.google.protobuf.AbstractParser<MetricDatumRequest>() {
      public MetricDatumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetricDatumRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MetricDatumRequest> getParserForType() {
      return PARSER;
    }

    public interface MapFieldEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string key = 1;
      /**
       * <code>optional string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>optional string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // optional string value = 2;
      /**
       * <code>optional string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry}
     *
     * <pre>
     * 针对该条数据的一些备注信息，例如最大值产生的时间：maxTime=1509724800，数据异常isInvalid=true，该时间点上的操作action=开机
     * 不应该把pointId的维度信息放在此字段，例如传感器Id，机器名称等，这些都是pointId的限定信息
     * </pre>
     */
    public static final class MapFieldEntry extends
        com.google.protobuf.GeneratedMessage
        implements MapFieldEntryOrBuilder {
      // Use MapFieldEntry.newBuilder() to construct.
      private MapFieldEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MapFieldEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MapFieldEntry defaultInstance;
      public static MapFieldEntry getDefaultInstance() {
        return defaultInstance;
      }

      public MapFieldEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MapFieldEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.class, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder.class);
      }

      public static com.google.protobuf.Parser<MapFieldEntry> PARSER =
          new com.google.protobuf.AbstractParser<MapFieldEntry>() {
        public MapFieldEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MapFieldEntry(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MapFieldEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry}
       *
       * <pre>
       * 针对该条数据的一些备注信息，例如最大值产生的时间：maxTime=1509724800，数据异常isInvalid=true，该时间点上的操作action=开机
       * 不应该把pointId的维度信息放在此字段，例如传感器Id，机器名称等，这些都是pointId的限定信息
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.class, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder.class);
        }

        // Construct using net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor;
        }

        public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry getDefaultInstanceForType() {
          return net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.getDefaultInstance();
        }

        public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry build() {
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry buildPartial() {
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry result = new net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry) {
            return mergeFrom((net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry other) {
          if (other == net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>optional string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // optional string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>optional string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry)
      }

      static {
        defaultInstance = new MapFieldEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry)
    }

    private int bitField0_;
    // required int64 pointId = 1;
    public static final int POINTID_FIELD_NUMBER = 1;
    private long pointId_;
    /**
     * <code>required int64 pointId = 1;</code>
     */
    public boolean hasPointId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 pointId = 1;</code>
     */
    public long getPointId() {
      return pointId_;
    }

    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *数据采集时间戳，距离1970年1月1日原点的毫秒数。
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *数据采集时间戳，距离1970年1月1日原点的毫秒数。
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required bytes value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 3;</code>
     *
     * <pre>
     *测量点在该时间点上对应的值
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes value = 3;</code>
     *
     * <pre>
     *测量点在该时间点上对应的值
     * </pre>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;
    public static final int NOTES_FIELD_NUMBER = 4;
    private java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> notes_;
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    public java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> getNotesList() {
      return notes_;
    }
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    public java.util.List<? extends net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder> 
        getNotesOrBuilderList() {
      return notes_;
    }
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    public int getNotesCount() {
      return notes_.size();
    }
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry getNotes(int index) {
      return notes_.get(index);
    }
    /**
     * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
     */
    public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder getNotesOrBuilder(
        int index) {
      return notes_.get(index);
    }

    private void initFields() {
      pointId_ = 0L;
      timestamp_ = 0L;
      value_ = com.google.protobuf.ByteString.EMPTY;
      notes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPointId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, pointId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, value_);
      }
      for (int i = 0; i < notes_.size(); i++) {
        output.writeMessage(4, notes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, pointId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      for (int i = 0; i < notes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, notes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.kylindb.analyser.mq.MetricDatumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.kylindb.analyser.mq.MetricDatum.MetricDatumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.class, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.Builder.class);
      }

      // Construct using net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNotesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pointId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (notesBuilder_ == null) {
          notes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          notesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.kylindb.analyser.mq.MetricDatum.internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor;
      }

      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest getDefaultInstanceForType() {
        return net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.getDefaultInstance();
      }

      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest build() {
        net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest buildPartial() {
        net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest result = new net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pointId_ = pointId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (notesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            notes_ = java.util.Collections.unmodifiableList(notes_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.notes_ = notes_;
        } else {
          result.notes_ = notesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest) {
          return mergeFrom((net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest other) {
        if (other == net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.getDefaultInstance()) return this;
        if (other.hasPointId()) {
          setPointId(other.getPointId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (notesBuilder_ == null) {
          if (!other.notes_.isEmpty()) {
            if (notes_.isEmpty()) {
              notes_ = other.notes_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureNotesIsMutable();
              notes_.addAll(other.notes_);
            }
            onChanged();
          }
        } else {
          if (!other.notes_.isEmpty()) {
            if (notesBuilder_.isEmpty()) {
              notesBuilder_.dispose();
              notesBuilder_ = null;
              notes_ = other.notes_;
              bitField0_ = (bitField0_ & ~0x00000008);
              notesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNotesFieldBuilder() : null;
            } else {
              notesBuilder_.addAllMessages(other.notes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPointId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 pointId = 1;
      private long pointId_ ;
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public boolean hasPointId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public long getPointId() {
        return pointId_;
      }
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public Builder setPointId(long value) {
        bitField0_ |= 0x00000001;
        pointId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public Builder clearPointId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pointId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required bytes value = 3;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;
      private java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> notes_ =
        java.util.Collections.emptyList();
      private void ensureNotesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          notes_ = new java.util.ArrayList<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry>(notes_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder> notesBuilder_;

      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> getNotesList() {
        if (notesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notes_);
        } else {
          return notesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public int getNotesCount() {
        if (notesBuilder_ == null) {
          return notes_.size();
        } else {
          return notesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry getNotes(int index) {
        if (notesBuilder_ == null) {
          return notes_.get(index);
        } else {
          return notesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder setNotes(
          int index, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.set(index, value);
          onChanged();
        } else {
          notesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder setNotes(
          int index, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.set(index, builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder addNotes(net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.add(value);
          onChanged();
        } else {
          notesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder addNotes(
          int index, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.add(index, value);
          onChanged();
        } else {
          notesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder addNotes(
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.add(builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder addNotes(
          int index, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.add(index, builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder addAllNotes(
          java.lang.Iterable<? extends net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry> values) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          super.addAll(values, notes_);
          onChanged();
        } else {
          notesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder clearNotes() {
        if (notesBuilder_ == null) {
          notes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          notesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public Builder removeNotes(int index) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.remove(index);
          onChanged();
        } else {
          notesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder getNotesBuilder(
          int index) {
        return getNotesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder getNotesOrBuilder(
          int index) {
        if (notesBuilder_ == null) {
          return notes_.get(index);  } else {
          return notesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public java.util.List<? extends net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder> 
           getNotesOrBuilderList() {
        if (notesBuilder_ != null) {
          return notesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notes_);
        }
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder addNotesBuilder() {
        return getNotesFieldBuilder().addBuilder(
            net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder addNotesBuilder(
          int index) {
        return getNotesFieldBuilder().addBuilder(
            index, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.analyser.mq.MetricDatumRequest.MapFieldEntry notes = 4;</code>
       */
      public java.util.List<net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder> 
           getNotesBuilderList() {
        return getNotesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder> 
          getNotesFieldBuilder() {
        if (notesBuilder_ == null) {
          notesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntry.Builder, net.kylindb.analyser.mq.MetricDatum.MetricDatumRequest.MapFieldEntryOrBuilder>(
                  notes_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          notes_ = null;
        }
        return notesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.kylindb.analyser.mq.MetricDatumRequest)
    }

    static {
      defaultInstance = new MetricDatumRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.kylindb.analyser.mq.MetricDatumRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_analyser_mq_MetricDatumRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021metricDatum.proto\022\027net.kylindb.analyse" +
      "r.mq\"\276\001\n\022MetricDatumRequest\022\017\n\007pointId\030\001" +
      " \002(\003\022\021\n\ttimestamp\030\002 \002(\003\022\r\n\005value\030\003 \002(\014\022H" +
      "\n\005notes\030\004 \003(\01329.net.kylindb.analyser.mq." +
      "MetricDatumRequest.MapFieldEntry\032+\n\rMapF" +
      "ieldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\rB" +
      "\013MetricDatum"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_kylindb_analyser_mq_MetricDatumRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor,
              new java.lang.String[] { "PointId", "Timestamp", "Value", "Notes", });
          internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor =
            internal_static_net_kylindb_analyser_mq_MetricDatumRequest_descriptor.getNestedTypes().get(0);
          internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_analyser_mq_MetricDatumRequest_MapFieldEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
