// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricData.proto

package net.kylindb.test.controller.mq;

public final class MetricData {
  private MetricData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetricDataRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> 
        getMetricDataList();
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum getMetricData(int index);
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    int getMetricDataCount();
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder> 
        getMetricDataOrBuilderList();
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder getMetricDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest}
   */
  public static final class MetricDataRequest extends
      com.google.protobuf.GeneratedMessage
      implements MetricDataRequestOrBuilder {
    // Use MetricDataRequest.newBuilder() to construct.
    private MetricDataRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MetricDataRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MetricDataRequest defaultInstance;
    public static MetricDataRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MetricDataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MetricDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                metricData_ = new java.util.ArrayList<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum>();
                mutable_bitField0_ |= 0x00000001;
              }
              metricData_.add(input.readMessage(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          metricData_ = java.util.Collections.unmodifiableList(metricData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.kylindb.test.controller.mq.MetricData.MetricDataRequest.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MetricDataRequest> PARSER =
        new com.google.protobuf.AbstractParser<MetricDataRequest>() {
      public MetricDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetricDataRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MetricDataRequest> getParserForType() {
      return PARSER;
    }

    public interface MetricDatumOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int64 pointId = 1;
      /**
       * <code>required int64 pointId = 1;</code>
       */
      boolean hasPointId();
      /**
       * <code>required int64 pointId = 1;</code>
       */
      long getPointId();

      // required int64 timestamp = 2;
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      boolean hasTimestamp();
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      long getTimestamp();

      // required bytes value = 3;
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      boolean hasValue();
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      com.google.protobuf.ByteString getValue();

      // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> 
          getNotesList();
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry getNotes(int index);
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      int getNotesCount();
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder> 
          getNotesOrBuilderList();
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder getNotesOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest.MetricDatum}
     */
    public static final class MetricDatum extends
        com.google.protobuf.GeneratedMessage
        implements MetricDatumOrBuilder {
      // Use MetricDatum.newBuilder() to construct.
      private MetricDatum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MetricDatum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MetricDatum defaultInstance;
      public static MetricDatum getDefaultInstance() {
        return defaultInstance;
      }

      public MetricDatum getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MetricDatum(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                pointId_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                timestamp_ = input.readInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                value_ = input.readBytes();
                break;
              }
              case 34: {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  notes_ = new java.util.ArrayList<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry>();
                  mutable_bitField0_ |= 0x00000008;
                }
                notes_.add(input.readMessage(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            notes_ = java.util.Collections.unmodifiableList(notes_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder.class);
      }

      public static com.google.protobuf.Parser<MetricDatum> PARSER =
          new com.google.protobuf.AbstractParser<MetricDatum>() {
        public MetricDatum parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetricDatum(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MetricDatum> getParserForType() {
        return PARSER;
      }

      public interface MapFieldEntryOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

        // optional string key = 1;
        /**
         * <code>optional string key = 1;</code>
         */
        boolean hasKey();
        /**
         * <code>optional string key = 1;</code>
         */
        java.lang.String getKey();
        /**
         * <code>optional string key = 1;</code>
         */
        com.google.protobuf.ByteString
            getKeyBytes();

        // optional string value = 2;
        /**
         * <code>optional string value = 2;</code>
         */
        boolean hasValue();
        /**
         * <code>optional string value = 2;</code>
         */
        java.lang.String getValue();
        /**
         * <code>optional string value = 2;</code>
         */
        com.google.protobuf.ByteString
            getValueBytes();
      }
      /**
       * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry}
       *
       * <pre>
       * 针对该条数据的一些备注信息，例如最大值产生的时间：maxTime=1509724800，数据异常isInvalid=true，该时间点上的操作action=开机
       * 不应该把pointId的维度信息放在此字段，例如传感器Id，机器名称等，这些都是pointId的限定信息
       * </pre>
       */
      public static final class MapFieldEntry extends
          com.google.protobuf.GeneratedMessage
          implements MapFieldEntryOrBuilder {
        // Use MapFieldEntry.newBuilder() to construct.
        private MapFieldEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
          super(builder);
          this.unknownFields = builder.getUnknownFields();
        }
        private MapFieldEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final MapFieldEntry defaultInstance;
        public static MapFieldEntry getDefaultInstance() {
          return defaultInstance;
        }

        public MapFieldEntry getDefaultInstanceForType() {
          return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
          return this.unknownFields;
        }
        private MapFieldEntry(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  key_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  value_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder.class);
        }

        public static com.google.protobuf.Parser<MapFieldEntry> PARSER =
            new com.google.protobuf.AbstractParser<MapFieldEntry>() {
          public MapFieldEntry parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new MapFieldEntry(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<MapFieldEntry> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // optional string key = 1;
        public static final int KEY_FIELD_NUMBER = 1;
        private java.lang.Object key_;
        /**
         * <code>optional string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        // optional string value = 2;
        public static final int VALUE_FIELD_NUMBER = 2;
        private java.lang.Object value_;
        /**
         * <code>optional string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private void initFields() {
          key_ = "";
          value_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getKeyBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeBytes(2, getValueBytes());
          }
          getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getKeyBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(2, getValueBytes());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry}
         *
         * <pre>
         * 针对该条数据的一些备注信息，例如最大值产生的时间：maxTime=1509724800，数据异常isInvalid=true，该时间点上的操作action=开机
         * 不应该把pointId的维度信息放在此字段，例如传感器Id，机器名称等，这些都是pointId的限定信息
         * </pre>
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor;
          }

          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder.class);
          }

          // Construct using net.kylindb.test.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            key_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            value_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor;
          }

          public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry getDefaultInstanceForType() {
            return net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.getDefaultInstance();
          }

          public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry build() {
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry buildPartial() {
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry result = new net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.key_ = key_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.value_ = value_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry) {
              return mergeFrom((net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry other) {
            if (other == net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.getDefaultInstance()) return this;
            if (other.hasKey()) {
              bitField0_ |= 0x00000001;
              key_ = other.key_;
              onChanged();
            }
            if (other.hasValue()) {
              bitField0_ |= 0x00000002;
              value_ = other.value_;
              onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // optional string key = 1;
          private java.lang.Object key_ = "";
          /**
           * <code>optional string key = 1;</code>
           */
          public boolean hasKey() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional string key = 1;</code>
           */
          public java.lang.String getKey() {
            java.lang.Object ref = key_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              key_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string key = 1;</code>
           */
          public com.google.protobuf.ByteString
              getKeyBytes() {
            java.lang.Object ref = key_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              key_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string key = 1;</code>
           */
          public Builder setKey(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            key_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string key = 1;</code>
           */
          public Builder clearKey() {
            bitField0_ = (bitField0_ & ~0x00000001);
            key_ = getDefaultInstance().getKey();
            onChanged();
            return this;
          }
          /**
           * <code>optional string key = 1;</code>
           */
          public Builder setKeyBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            key_ = value;
            onChanged();
            return this;
          }

          // optional string value = 2;
          private java.lang.Object value_ = "";
          /**
           * <code>optional string value = 2;</code>
           */
          public boolean hasValue() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>optional string value = 2;</code>
           */
          public java.lang.String getValue() {
            java.lang.Object ref = value_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              value_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string value = 2;</code>
           */
          public com.google.protobuf.ByteString
              getValueBytes() {
            java.lang.Object ref = value_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              value_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string value = 2;</code>
           */
          public Builder setValue(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            value_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string value = 2;</code>
           */
          public Builder clearValue() {
            bitField0_ = (bitField0_ & ~0x00000002);
            value_ = getDefaultInstance().getValue();
            onChanged();
            return this;
          }
          /**
           * <code>optional string value = 2;</code>
           */
          public Builder setValueBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            value_ = value;
            onChanged();
            return this;
          }

          // @@protoc_insertion_point(builder_scope:net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry)
        }

        static {
          defaultInstance = new MapFieldEntry(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry)
      }

      private int bitField0_;
      // required int64 pointId = 1;
      public static final int POINTID_FIELD_NUMBER = 1;
      private long pointId_;
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public boolean hasPointId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 pointId = 1;</code>
       */
      public long getPointId() {
        return pointId_;
      }

      // required int64 timestamp = 2;
      public static final int TIMESTAMP_FIELD_NUMBER = 2;
      private long timestamp_;
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *数据采集时间戳，距离1970年1月1日原点的毫秒数。
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      // required bytes value = 3;
      public static final int VALUE_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString value_;
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes value = 3;</code>
       *
       * <pre>
       *测量点在该时间点上对应的值
       * </pre>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }

      // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;
      public static final int NOTES_FIELD_NUMBER = 4;
      private java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> notes_;
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> getNotesList() {
        return notes_;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      public java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder> 
          getNotesOrBuilderList() {
        return notes_;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      public int getNotesCount() {
        return notes_.size();
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry getNotes(int index) {
        return notes_.get(index);
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder getNotesOrBuilder(
          int index) {
        return notes_.get(index);
      }

      private void initFields() {
        pointId_ = 0L;
        timestamp_ = 0L;
        value_ = com.google.protobuf.ByteString.EMPTY;
        notes_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPointId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, pointId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, timestamp_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, value_);
        }
        for (int i = 0; i < notes_.size(); i++) {
          output.writeMessage(4, notes_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, pointId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, timestamp_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, value_);
        }
        for (int i = 0; i < notes_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, notes_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest.MetricDatum}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder.class);
        }

        // Construct using net.kylindb.test.mq.MetricData.MetricDataRequest.MetricDatum.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getNotesFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          pointId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          if (notesBuilder_ == null) {
            notes_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            notesBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor;
        }

        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum getDefaultInstanceForType() {
          return net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.getDefaultInstance();
        }

        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum build() {
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum buildPartial() {
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum result = new net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.pointId_ = pointId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.value_ = value_;
          if (notesBuilder_ == null) {
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              notes_ = java.util.Collections.unmodifiableList(notes_);
              bitField0_ = (bitField0_ & ~0x00000008);
            }
            result.notes_ = notes_;
          } else {
            result.notes_ = notesBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum) {
            return mergeFrom((net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum other) {
          if (other == net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.getDefaultInstance()) return this;
          if (other.hasPointId()) {
            setPointId(other.getPointId());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (notesBuilder_ == null) {
            if (!other.notes_.isEmpty()) {
              if (notes_.isEmpty()) {
                notes_ = other.notes_;
                bitField0_ = (bitField0_ & ~0x00000008);
              } else {
                ensureNotesIsMutable();
                notes_.addAll(other.notes_);
              }
              onChanged();
            }
          } else {
            if (!other.notes_.isEmpty()) {
              if (notesBuilder_.isEmpty()) {
                notesBuilder_.dispose();
                notesBuilder_ = null;
                notes_ = other.notes_;
                bitField0_ = (bitField0_ & ~0x00000008);
                notesBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getNotesFieldBuilder() : null;
              } else {
                notesBuilder_.addAllMessages(other.notes_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPointId()) {
            
            return false;
          }
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int64 pointId = 1;
        private long pointId_ ;
        /**
         * <code>required int64 pointId = 1;</code>
         */
        public boolean hasPointId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 pointId = 1;</code>
         */
        public long getPointId() {
          return pointId_;
        }
        /**
         * <code>required int64 pointId = 1;</code>
         */
        public Builder setPointId(long value) {
          bitField0_ |= 0x00000001;
          pointId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 pointId = 1;</code>
         */
        public Builder clearPointId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          pointId_ = 0L;
          onChanged();
          return this;
        }

        // required int64 timestamp = 2;
        private long timestamp_ ;
        /**
         * <code>required int64 timestamp = 2;</code>
         *
         * <pre>
         *数据采集时间戳，距离1970年1月1日原点的毫秒数。
         * </pre>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 timestamp = 2;</code>
         *
         * <pre>
         *数据采集时间戳，距离1970年1月1日原点的毫秒数。
         * </pre>
         */
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int64 timestamp = 2;</code>
         *
         * <pre>
         *数据采集时间戳，距离1970年1月1日原点的毫秒数。
         * </pre>
         */
        public Builder setTimestamp(long value) {
          bitField0_ |= 0x00000002;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 timestamp = 2;</code>
         *
         * <pre>
         *数据采集时间戳，距离1970年1月1日原点的毫秒数。
         * </pre>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        // required bytes value = 3;
        private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes value = 3;</code>
         *
         * <pre>
         *测量点在该时间点上对应的值
         * </pre>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bytes value = 3;</code>
         *
         * <pre>
         *测量点在该时间点上对应的值
         * </pre>
         */
        public com.google.protobuf.ByteString getValue() {
          return value_;
        }
        /**
         * <code>required bytes value = 3;</code>
         *
         * <pre>
         *测量点在该时间点上对应的值
         * </pre>
         */
        public Builder setValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes value = 3;</code>
         *
         * <pre>
         *测量点在该时间点上对应的值
         * </pre>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000004);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }

        // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;
        private java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> notes_ =
          java.util.Collections.emptyList();
        private void ensureNotesIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            notes_ = new java.util.ArrayList<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry>(notes_);
            bitField0_ |= 0x00000008;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder> notesBuilder_;

        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> getNotesList() {
          if (notesBuilder_ == null) {
            return java.util.Collections.unmodifiableList(notes_);
          } else {
            return notesBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public int getNotesCount() {
          if (notesBuilder_ == null) {
            return notes_.size();
          } else {
            return notesBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry getNotes(int index) {
          if (notesBuilder_ == null) {
            return notes_.get(index);
          } else {
            return notesBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder setNotes(
            int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry value) {
          if (notesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNotesIsMutable();
            notes_.set(index, value);
            onChanged();
          } else {
            notesBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder setNotes(
            int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder builderForValue) {
          if (notesBuilder_ == null) {
            ensureNotesIsMutable();
            notes_.set(index, builderForValue.build());
            onChanged();
          } else {
            notesBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder addNotes(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry value) {
          if (notesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNotesIsMutable();
            notes_.add(value);
            onChanged();
          } else {
            notesBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder addNotes(
            int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry value) {
          if (notesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNotesIsMutable();
            notes_.add(index, value);
            onChanged();
          } else {
            notesBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder addNotes(
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder builderForValue) {
          if (notesBuilder_ == null) {
            ensureNotesIsMutable();
            notes_.add(builderForValue.build());
            onChanged();
          } else {
            notesBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder addNotes(
            int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder builderForValue) {
          if (notesBuilder_ == null) {
            ensureNotesIsMutable();
            notes_.add(index, builderForValue.build());
            onChanged();
          } else {
            notesBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder addAllNotes(
            java.lang.Iterable<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry> values) {
          if (notesBuilder_ == null) {
            ensureNotesIsMutable();
            super.addAll(values, notes_);
            onChanged();
          } else {
            notesBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder clearNotes() {
          if (notesBuilder_ == null) {
            notes_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
          } else {
            notesBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public Builder removeNotes(int index) {
          if (notesBuilder_ == null) {
            ensureNotesIsMutable();
            notes_.remove(index);
            onChanged();
          } else {
            notesBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder getNotesBuilder(
            int index) {
          return getNotesFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder getNotesOrBuilder(
            int index) {
          if (notesBuilder_ == null) {
            return notes_.get(index);  } else {
            return notesBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder> 
             getNotesOrBuilderList() {
          if (notesBuilder_ != null) {
            return notesBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(notes_);
          }
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder addNotesBuilder() {
          return getNotesFieldBuilder().addBuilder(
              net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.getDefaultInstance());
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder addNotesBuilder(
            int index) {
          return getNotesFieldBuilder().addBuilder(
              index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.getDefaultInstance());
        }
        /**
         * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum.MapFieldEntry notes = 4;</code>
         */
        public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder> 
             getNotesBuilderList() {
          return getNotesFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder> 
            getNotesFieldBuilder() {
          if (notesBuilder_ == null) {
            notesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntry.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.MapFieldEntryOrBuilder>(
                    notes_,
                    ((bitField0_ & 0x00000008) == 0x00000008),
                    getParentForChildren(),
                    isClean());
            notes_ = null;
          }
          return notesBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:net.kylindb.test.mq.MetricDataRequest.MetricDatum)
      }

      static {
        defaultInstance = new MetricDatum(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.kylindb.test.mq.MetricDataRequest.MetricDatum)
    }

    // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;
    public static final int METRICDATA_FIELD_NUMBER = 1;
    private java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> metricData_;
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> getMetricDataList() {
      return metricData_;
    }
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    public java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder> 
        getMetricDataOrBuilderList() {
      return metricData_;
    }
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    public int getMetricDataCount() {
      return metricData_.size();
    }
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum getMetricData(int index) {
      return metricData_.get(index);
    }
    /**
     * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
     */
    public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder getMetricDataOrBuilder(
        int index) {
      return metricData_.get(index);
    }

    private void initFields() {
      metricData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMetricDataCount(); i++) {
        if (!getMetricData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < metricData_.size(); i++) {
        output.writeMessage(1, metricData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < metricData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, metricData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.test.controller.mq.MetricData.MetricDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.kylindb.test.controller.mq.MetricData.MetricDataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.kylindb.test.mq.MetricDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.kylindb.test.controller.mq.MetricData.MetricDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.test.controller.mq.MetricData.MetricDataRequest.class, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.Builder.class);
      }

      // Construct using net.kylindb.test.mq.MetricData.MetricDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetricDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (metricDataBuilder_ == null) {
          metricData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          metricDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.kylindb.test.controller.mq.MetricData.internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor;
      }

      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest getDefaultInstanceForType() {
        return net.kylindb.test.controller.mq.MetricData.MetricDataRequest.getDefaultInstance();
      }

      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest build() {
        net.kylindb.test.controller.mq.MetricData.MetricDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest buildPartial() {
        net.kylindb.test.controller.mq.MetricData.MetricDataRequest result = new net.kylindb.test.controller.mq.MetricData.MetricDataRequest(this);
        int from_bitField0_ = bitField0_;
        if (metricDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            metricData_ = java.util.Collections.unmodifiableList(metricData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.metricData_ = metricData_;
        } else {
          result.metricData_ = metricDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.kylindb.test.controller.mq.MetricData.MetricDataRequest) {
          return mergeFrom((net.kylindb.test.controller.mq.MetricData.MetricDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.kylindb.test.controller.mq.MetricData.MetricDataRequest other) {
        if (other == net.kylindb.test.controller.mq.MetricData.MetricDataRequest.getDefaultInstance()) return this;
        if (metricDataBuilder_ == null) {
          if (!other.metricData_.isEmpty()) {
            if (metricData_.isEmpty()) {
              metricData_ = other.metricData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMetricDataIsMutable();
              metricData_.addAll(other.metricData_);
            }
            onChanged();
          }
        } else {
          if (!other.metricData_.isEmpty()) {
            if (metricDataBuilder_.isEmpty()) {
              metricDataBuilder_.dispose();
              metricDataBuilder_ = null;
              metricData_ = other.metricData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              metricDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetricDataFieldBuilder() : null;
            } else {
              metricDataBuilder_.addAllMessages(other.metricData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMetricDataCount(); i++) {
          if (!getMetricData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.kylindb.test.controller.mq.MetricData.MetricDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.kylindb.test.controller.mq.MetricData.MetricDataRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;
      private java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> metricData_ =
        java.util.Collections.emptyList();
      private void ensureMetricDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          metricData_ = new java.util.ArrayList<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum>(metricData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder> metricDataBuilder_;

      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> getMetricDataList() {
        if (metricDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metricData_);
        } else {
          return metricDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public int getMetricDataCount() {
        if (metricDataBuilder_ == null) {
          return metricData_.size();
        } else {
          return metricDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum getMetricData(int index) {
        if (metricDataBuilder_ == null) {
          return metricData_.get(index);
        } else {
          return metricDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder setMetricData(
          int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum value) {
        if (metricDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricDataIsMutable();
          metricData_.set(index, value);
          onChanged();
        } else {
          metricDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder setMetricData(
          int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder builderForValue) {
        if (metricDataBuilder_ == null) {
          ensureMetricDataIsMutable();
          metricData_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder addMetricData(net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum value) {
        if (metricDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricDataIsMutable();
          metricData_.add(value);
          onChanged();
        } else {
          metricDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder addMetricData(
          int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum value) {
        if (metricDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricDataIsMutable();
          metricData_.add(index, value);
          onChanged();
        } else {
          metricDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder addMetricData(
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder builderForValue) {
        if (metricDataBuilder_ == null) {
          ensureMetricDataIsMutable();
          metricData_.add(builderForValue.build());
          onChanged();
        } else {
          metricDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder addMetricData(
          int index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder builderForValue) {
        if (metricDataBuilder_ == null) {
          ensureMetricDataIsMutable();
          metricData_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder addAllMetricData(
          java.lang.Iterable<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum> values) {
        if (metricDataBuilder_ == null) {
          ensureMetricDataIsMutable();
          super.addAll(values, metricData_);
          onChanged();
        } else {
          metricDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder clearMetricData() {
        if (metricDataBuilder_ == null) {
          metricData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          metricDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public Builder removeMetricData(int index) {
        if (metricDataBuilder_ == null) {
          ensureMetricDataIsMutable();
          metricData_.remove(index);
          onChanged();
        } else {
          metricDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder getMetricDataBuilder(
          int index) {
        return getMetricDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder getMetricDataOrBuilder(
          int index) {
        if (metricDataBuilder_ == null) {
          return metricData_.get(index);  } else {
          return metricDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public java.util.List<? extends net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder> 
           getMetricDataOrBuilderList() {
        if (metricDataBuilder_ != null) {
          return metricDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metricData_);
        }
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder addMetricDataBuilder() {
        return getMetricDataFieldBuilder().addBuilder(
            net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder addMetricDataBuilder(
          int index) {
        return getMetricDataFieldBuilder().addBuilder(
            index, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.test.mq.MetricDataRequest.MetricDatum metricData = 1;</code>
       */
      public java.util.List<net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder> 
           getMetricDataBuilderList() {
        return getMetricDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder> 
          getMetricDataFieldBuilder() {
        if (metricDataBuilder_ == null) {
          metricDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatum.Builder, net.kylindb.test.controller.mq.MetricData.MetricDataRequest.MetricDatumOrBuilder>(
                  metricData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          metricData_ = null;
        }
        return metricDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.kylindb.test.mq.MetricDataRequest)
    }

    static {
      defaultInstance = new MetricDataRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.kylindb.test.mq.MetricDataRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_test_mq_MetricDataRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020metricData.proto\022\033net.kylindb.metricWr" +
      "iter.mq\"\254\002\n\021MetricDataRequest\022N\n\nmetricD" +
      "ata\030\001 \003(\0132:.net.kylindb.test.mq." +
      "MetricDataRequest.MetricDatum\032\306\001\n\013Metric" +
      "Datum\022\017\n\007pointId\030\001 \002(\003\022\021\n\ttimestamp\030\002 \002(" +
      "\003\022\r\n\005value\030\003 \002(\014\022W\n\005notes\030\004 \003(\0132H.net.ky" +
      "lindb.test.mq.MetricDataRequest." +
      "MetricDatum.MapFieldEntry\032+\n\rMapFieldEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\014B\nMetric" +
      "Data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_kylindb_test_mq_MetricDataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor,
              new java.lang.String[] { "MetricData", });
          internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor =
            internal_static_net_kylindb_test_mq_MetricDataRequest_descriptor.getNestedTypes().get(0);
          internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor,
              new java.lang.String[] { "PointId", "Timestamp", "Value", "Notes", });
          internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor =
            internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_descriptor.getNestedTypes().get(0);
          internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_test_mq_MetricDataRequest_MetricDatum_MapFieldEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
