// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noteData.proto

package net.kylindb.coder;

public final class NotesMap {
  private NotesMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NoteDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> 
        getNotesList();
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    net.kylindb.coder.NotesMap.NoteData.MapFieldEntry getNotes(int index);
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    int getNotesCount();
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    java.util.List<? extends net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder> 
        getNotesOrBuilderList();
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder getNotesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.kylindb.coder.NoteData}
   */
  public static final class NoteData extends
      com.google.protobuf.GeneratedMessage
      implements NoteDataOrBuilder {
    // Use NoteData.newBuilder() to construct.
    private NoteData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NoteData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NoteData defaultInstance;
    public static NoteData getDefaultInstance() {
      return defaultInstance;
    }

    public NoteData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NoteData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                notes_ = new java.util.ArrayList<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              notes_.add(input.readMessage(net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = java.util.Collections.unmodifiableList(notes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.kylindb.coder.NotesMap.NoteData.class, net.kylindb.coder.NotesMap.NoteData.Builder.class);
    }

    public static com.google.protobuf.Parser<NoteData> PARSER =
        new com.google.protobuf.AbstractParser<NoteData>() {
      public NoteData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NoteData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NoteData> getParserForType() {
      return PARSER;
    }

    public interface MapFieldEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string key = 1;
      /**
       * <code>optional string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>optional string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // optional string value = 2;
      /**
       * <code>optional string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code net.kylindb.coder.NoteData.MapFieldEntry}
     */
    public static final class MapFieldEntry extends
        com.google.protobuf.GeneratedMessage
        implements MapFieldEntryOrBuilder {
      // Use MapFieldEntry.newBuilder() to construct.
      private MapFieldEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MapFieldEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MapFieldEntry defaultInstance;
      public static MapFieldEntry getDefaultInstance() {
        return defaultInstance;
      }

      public MapFieldEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MapFieldEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_MapFieldEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.class, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder.class);
      }

      public static com.google.protobuf.Parser<MapFieldEntry> PARSER =
          new com.google.protobuf.AbstractParser<MapFieldEntry>() {
        public MapFieldEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MapFieldEntry(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MapFieldEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.kylindb.coder.NotesMap.NoteData.MapFieldEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.kylindb.coder.NoteData.MapFieldEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_MapFieldEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.class, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder.class);
        }

        // Construct using net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor;
        }

        public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry getDefaultInstanceForType() {
          return net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.getDefaultInstance();
        }

        public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry build() {
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry buildPartial() {
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry result = new net.kylindb.coder.NotesMap.NoteData.MapFieldEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.kylindb.coder.NotesMap.NoteData.MapFieldEntry) {
            return mergeFrom((net.kylindb.coder.NotesMap.NoteData.MapFieldEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.kylindb.coder.NotesMap.NoteData.MapFieldEntry other) {
          if (other == net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.kylindb.coder.NotesMap.NoteData.MapFieldEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>optional string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // optional string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>optional string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.kylindb.coder.NoteData.MapFieldEntry)
      }

      static {
        defaultInstance = new MapFieldEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.kylindb.coder.NoteData.MapFieldEntry)
    }

    // repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;
    public static final int NOTES_FIELD_NUMBER = 1;
    private java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> notes_;
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    public java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> getNotesList() {
      return notes_;
    }
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    public java.util.List<? extends net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder> 
        getNotesOrBuilderList() {
      return notes_;
    }
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    public int getNotesCount() {
      return notes_.size();
    }
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry getNotes(int index) {
      return notes_.get(index);
    }
    /**
     * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
     */
    public net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder getNotesOrBuilder(
        int index) {
      return notes_.get(index);
    }

    private void initFields() {
      notes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < notes_.size(); i++) {
        output.writeMessage(1, notes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < notes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, notes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.kylindb.coder.NotesMap.NoteData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.kylindb.coder.NotesMap.NoteData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.kylindb.coder.NoteData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.kylindb.coder.NotesMap.NoteDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.kylindb.coder.NotesMap.NoteData.class, net.kylindb.coder.NotesMap.NoteData.Builder.class);
      }

      // Construct using net.kylindb.coder.NotesMap.NoteData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNotesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (notesBuilder_ == null) {
          notes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          notesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.kylindb.coder.NotesMap.internal_static_net_kylindb_coder_NoteData_descriptor;
      }

      public net.kylindb.coder.NotesMap.NoteData getDefaultInstanceForType() {
        return net.kylindb.coder.NotesMap.NoteData.getDefaultInstance();
      }

      public net.kylindb.coder.NotesMap.NoteData build() {
        net.kylindb.coder.NotesMap.NoteData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.kylindb.coder.NotesMap.NoteData buildPartial() {
        net.kylindb.coder.NotesMap.NoteData result = new net.kylindb.coder.NotesMap.NoteData(this);
        int from_bitField0_ = bitField0_;
        if (notesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            notes_ = java.util.Collections.unmodifiableList(notes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.notes_ = notes_;
        } else {
          result.notes_ = notesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.kylindb.coder.NotesMap.NoteData) {
          return mergeFrom((net.kylindb.coder.NotesMap.NoteData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.kylindb.coder.NotesMap.NoteData other) {
        if (other == net.kylindb.coder.NotesMap.NoteData.getDefaultInstance()) return this;
        if (notesBuilder_ == null) {
          if (!other.notes_.isEmpty()) {
            if (notes_.isEmpty()) {
              notes_ = other.notes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNotesIsMutable();
              notes_.addAll(other.notes_);
            }
            onChanged();
          }
        } else {
          if (!other.notes_.isEmpty()) {
            if (notesBuilder_.isEmpty()) {
              notesBuilder_.dispose();
              notesBuilder_ = null;
              notes_ = other.notes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              notesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNotesFieldBuilder() : null;
            } else {
              notesBuilder_.addAllMessages(other.notes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.kylindb.coder.NotesMap.NoteData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.kylindb.coder.NotesMap.NoteData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;
      private java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> notes_ =
        java.util.Collections.emptyList();
      private void ensureNotesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = new java.util.ArrayList<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry>(notes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder, net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder> notesBuilder_;

      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> getNotesList() {
        if (notesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notes_);
        } else {
          return notesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public int getNotesCount() {
        if (notesBuilder_ == null) {
          return notes_.size();
        } else {
          return notesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry getNotes(int index) {
        if (notesBuilder_ == null) {
          return notes_.get(index);
        } else {
          return notesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder setNotes(
          int index, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.set(index, value);
          onChanged();
        } else {
          notesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder setNotes(
          int index, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.set(index, builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder addNotes(net.kylindb.coder.NotesMap.NoteData.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.add(value);
          onChanged();
        } else {
          notesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder addNotes(
          int index, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry value) {
        if (notesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotesIsMutable();
          notes_.add(index, value);
          onChanged();
        } else {
          notesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder addNotes(
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.add(builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder addNotes(
          int index, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder builderForValue) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.add(index, builderForValue.build());
          onChanged();
        } else {
          notesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder addAllNotes(
          java.lang.Iterable<? extends net.kylindb.coder.NotesMap.NoteData.MapFieldEntry> values) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          super.addAll(values, notes_);
          onChanged();
        } else {
          notesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder clearNotes() {
        if (notesBuilder_ == null) {
          notes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          notesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public Builder removeNotes(int index) {
        if (notesBuilder_ == null) {
          ensureNotesIsMutable();
          notes_.remove(index);
          onChanged();
        } else {
          notesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder getNotesBuilder(
          int index) {
        return getNotesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder getNotesOrBuilder(
          int index) {
        if (notesBuilder_ == null) {
          return notes_.get(index);  } else {
          return notesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public java.util.List<? extends net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder> 
           getNotesOrBuilderList() {
        if (notesBuilder_ != null) {
          return notesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notes_);
        }
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder addNotesBuilder() {
        return getNotesFieldBuilder().addBuilder(
            net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder addNotesBuilder(
          int index) {
        return getNotesFieldBuilder().addBuilder(
            index, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .net.kylindb.coder.NoteData.MapFieldEntry notes = 1;</code>
       */
      public java.util.List<net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder> 
           getNotesBuilderList() {
        return getNotesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.kylindb.coder.NotesMap.NoteData.MapFieldEntry, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder, net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder> 
          getNotesFieldBuilder() {
        if (notesBuilder_ == null) {
          notesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.kylindb.coder.NotesMap.NoteData.MapFieldEntry, net.kylindb.coder.NotesMap.NoteData.MapFieldEntry.Builder, net.kylindb.coder.NotesMap.NoteData.MapFieldEntryOrBuilder>(
                  notes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          notes_ = null;
        }
        return notesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.kylindb.coder.NoteData)
    }

    static {
      defaultInstance = new NoteData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.kylindb.coder.NoteData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_coder_NoteData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_coder_NoteData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_kylindb_coder_NoteData_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016noteData.proto\022\021net.kylindb.coder\"q\n\010N" +
      "oteData\0228\n\005notes\030\001 \003(\0132).net.kylindb.cod" +
      "er.NoteData.MapFieldEntry\032+\n\rMapFieldEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\nB\010NotesM" +
      "ap"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_kylindb_coder_NoteData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_kylindb_coder_NoteData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_coder_NoteData_descriptor,
              new java.lang.String[] { "Notes", });
          internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor =
            internal_static_net_kylindb_coder_NoteData_descriptor.getNestedTypes().get(0);
          internal_static_net_kylindb_coder_NoteData_MapFieldEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_kylindb_coder_NoteData_MapFieldEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
